import express, { Application } from 'express';
const app: Application = express();
import cors from 'cors';
import globalErrorHandler from './app/middleWares/globalErrorHandlers';
import router from './routes';
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/api/v1', router);
app.use(globalErrorHandler);
export default app;
